# WhatATheme
markdown: markdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: balmung个人主页
# Description of the Site
description: rage against the dying of the light
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Blog, Programming
# URL for the Image of custom Favicon
favicon-url: /assets/images/test.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 1070627093@qq.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  balmung08
youtube_channel_id:
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
steam_username:  76561198898860590
wyy_username: 101697166
bilibili_username: 184704138

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: balmung08

# Name of the Author
author-name: balmung08
# URL for the Image of the Author
author-image: ../assets/images/test.jpg
# 60 Words About the Author
author-about: 工科人，学控制的，活的，读研混子<br>主要技术栈：嵌入式、CV、控制规划<br>淡坑mug玩家/sv ocg player/jrpg死忠/apex真好玩

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/balmung08

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'postsc'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
