title: Personal Homepage
description: Do not go gentle into that good night, Old age should burn and rave at close of day, Rage, rage against the dying of the light.
author: Runjiao Bao
# author_bio: In this new era, AI feels increasingly human, people feel increasingly artificial.
avatar: /pic/author.jpg
email: 3120230765@bit.edu.cn
disqus: balmung08
subscribe: False
location: China, Beijing
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Runjiao Bao
  links:
    - https://github.com/balmung08
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
skin: sunrise
